apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-cwa-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cwa.storage }}
  storageClassName: {{ .Values.cwa.storageClass }}
