apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-config-secret
spec:
  itemPath: {{ required "A Secret-Reference for the config must be provided" .Values.secrets.configSecretRef }}
