xxx:
  resources:
    requests:
      cpu: 0.1
      memory: 512Mi
      ephemeral-storage: 10Mi
    limits:
      cpu: 1
      memory: 768Mi
      ephemeral-storage: 100Mi

ingress:
  enabled: true
  clusterIssuer: letsencrypt
  domain: null