kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.patchmon.storage.size }}
  {{- if .Values.patchmon.storage.storageClass }}
  storageClassName: {{ .Values.patchmon.storage.class }}
  {{- end }}