apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgres-secret
spec:
  itemPath: {{ required "A secret-reference for the Postgres-Secret must be provided" .Values.secrets.postgresSecretRef }}
