apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-oidc-secret
spec:
  itemPath: {{ required "You must provide a oidcSecret Reference" .Values.secrets.oidcSecretRef }}
