apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
spec:
  itemPath: {{ required "You must provide a voucherVaultSecret Reference" .Values.secrets.voucherVaultSecretRef }}
