{{- if .Values.smbConnection.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-smb-secret
spec:
  itemPath: {{ required "A secret-reference for the SMB-Connection-Secret must be provided" .Values.secrets.smbConnectionSecretRef }}
{{- end }}