matrix:
  serverName: null
  timezone: UTC
  configSecretRef: null
  delegation:
    enabled: false
    serverUrl: null

storage:
  amount: 10Gi
  storageClass: longhorn-encrypted

ingress:
  domain: null
  clusterIssuer: null